### PR TITLE
Update Drupal 9.5.x

### PR DESCRIPTION
**Pull request by sarahhghazali**
## What does this PR do?

- Updating Drupal plugin for version 9.5.x

### Relevant logs and/or screenshots

Testing performed using sandbox

INSTALL PLUGIN
image

image

ADD TO CART
1 add to cart

CHECKOUT
2 checkout

PAYMENT
3 payment

SUCCESS ORDER
success drupal

PENDING ORDER
pending drupal

FAILED ORDER
fail drupal

### CODE REVIEW

**Comment by muaz9019** [comment]
Hello, I have tried the 9.5.0 version and getting this:

when putting the module to my website, I am getting this error and cannot access my website
Screenshot 2023-01-17 162147

the error log is as attach: 
[error_wsod.txt](https://github.com/RazerMS/Shopping-Cart-Plugins-RazerMS_Drupal_Commerce_7/files/10432804/error_wsod.txt)

**Comment by muaz9019** [comment]
adding in "core_version_requirement: ^9" in file commerce_razermerchantservices_normal.yml fix the issue
Screenshot 2023-01-17 162920

**Comment by muaz9019** [comment]
Getting this error when trying to pay:
Screenshot 2023-01-17 163317
this are the error log:
[error_payment.txt](https://github.com/RazerMS/Shopping-Cart-Plugins-RazerMS_Drupal_Commerce_7/files/10432870/error_payment.txt)

**Comment by sarahhghazali** [comment]
> adding in "core_version_requirement: ^9" in file commerce_razermerchantservices_normal.yml fix the issue Screenshot 2023-01-17 162920

Thank you for letting us know. Will update suggested fix.

**Comment by sarahhghazali** [comment]
> Getting this error when trying to pay: Screenshot 2023-01-17 163317 this are the error log: [error_payment.txt](https://github.com/RazerMS/Shopping-Cart-Plugins-RazerMS_Drupal_Commerce_7/files/10432870/error_payment.txt)

Please make sure amount, orderID, verify key and merchantID is correct. For further discussion, you may join RMS Developer Forum Telegram Group https://github.com/RazerMS/Telegram-RMSDeveloperForum

**Pull request merged**
